### ISSUE TITLE
App crash when trying to login.

### ISSUE THREAD

**Issue by sakchhams** [UdacityAndroidDevScholarship/blood-donation#28]
### Environment
  * Version : develop 7bb6bd3e9b48d502584e714e9015ba2b4c9b3c39
  * Device/Operating System : Emulator x86 Android 8.1.1, Android Studio 3.1.1
  
### Bug:

  * What error did you encounter?
App force closed when trying to sign in.

> java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
        at com.google.android.gms.internal.zzdza.zzb(Unknown Source:4)
        at com.google.android.gms.internal.zzdzh.zza(Unknown Source:19)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:44)
        at com.google.firebase.auth.PhoneAuthProvider.zza(Unknown Source:18)
        at com.google.firebase.auth.PhoneAuthProvider.verifyPhoneNumber(Unknown Source:24)
        at com.udacity.nanodegree.blooddonation.ui.registration.view.UserRegistrationActivity.verifyPhoneNumber(UserRegistrationActivity.java:132)
        at com.udacity.nanodegree.blooddonation.ui.registration.presenter.UserRegistrationPresenter.onIamInButtonClick(UserRegistrationPresenter.java:36)
        at com.udacity.nanodegree.blooddonation.databinding.ActivityUserRegisBindingImpl._internalCallbackOnClick(ActivityUserRegisBindingImpl.java:368)
        at com.udacity.nanodegree.blooddonation.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

  * When does this occur? 
After entering a valid phone number and clicking I'm in. It crashes immediately.
#### Steps to reproduce:

  1. Open the app.
  2. Enter your phone number.
  3. Click on `I'm in`

**Comment by ritesh-singh** [comment]
Connect with firebase.
Enable phone signin method in firebase.

Run it in your phone as it needs sim, not emualator.

Will work fine.

**Comment by sakchhams** [comment]
@ritesh-singh it should not crash however.

**Comment by ritesh-singh** [comment]
@sakchhams It will not crash.
What are your finding on the same?

**Comment by sakchhams** [comment]
@ritesh-singh read the issue description.

**Comment by ritesh-singh** [comment]
I read. Run it on phone not emulator, you need sim right??

**Comment by sakchhams** [comment]
@ritesh-singh it should not crash anywhere in my opinion. And no you do not need a sim. It's an emulator, you can test out everything except Bluetooth.

**Comment by ritesh-singh** [comment]
No, it won't work. Not even it rooted device.
Checkout this
https://github.com/firebase/FirebaseUI-Android/issues/790

**Comment by ritesh-singh** [comment]
@sakchhams Let, me know if you find anything reading this.

**Comment by sakchhams** [comment]
@ritesh-singh The issue is the app crashing. Not the firebase authentication not working. The latter is acceptable. The former is not.

**Comment by ritesh-singh** [comment]
Will fix later, not a priority as of now.

Please, go ahead and fix, if you get time.
